---
title: "Leetcode Easy Questions -- Part 1"
author: "Wenxiao Zhou"
date: "3/23/2022"
output: html_document
---

**175. Combine Two Tables**\
Table `Person`: personId(int,primary key), lastName(varchar), firstName(varchar)\
This table contains information about the ID of some persons and their names.\
Table `Address`: addressId(int,primary key), personId(int), city(varchar), state(varchar)
Each row contains information about the city and state of one person with ID=PersonId

&NewLine;
**Goal:** Write an SQL query to report the `first name, last name, city, and state` of each person in the `Person` table. If the address of a `personId` is not present in the Address table, report null instead.\
Return the result table in any order.

&NewLine;
&NewLine;

**181. Employees Earning More Than Their Managers**\
Table `Employee`: id(int,primary key), name(varchar), salary(int), managerId(int)\

&NewLine;
**Goal:** Write an SQL query to find the employees who earn more than their managers.\
Return the result table in any order.


&NewLine;
&NewLine;



**182. Duplicate Emails**\
Table `Person`: id(int, primary key), email(varchar)\
Each row of this table contains an email. The emails will not contain uppercase letters.\

&NewLine;
Goal: Write an SQL query to report all the duplicate emails. Return the result table in any order.\



&NewLine;
&NewLine;

**183. Customers Who Never Order**\
Table `Customers`: id(int, primary key), name(varchar)\
Table `Orders`: id(int,primary key), customerId(int, foreign key of the ID from Customers table)\
Each row of this table indicates the ID of an order and the ID of the customer who ordered it.
 
&NewLine;
**Goal:** Write an SQL query to report all customers who never order anything.Return the result table in any order.



&NewLine;
&NewLine;

**196. Delete Duplicate Emails**\
Table `Person`: id(int, primary key), email(varchar)\

&NewLine;
**Goal:** Write an SQL query to delete all the duplicate emails, keeping only one unique email with the smallest id. Note that you are supposed to write a DELETE statement and not a SELECT one.\
Return the result table in any order.


&NewLine;
&NewLine;


**197. Rising Temperature**\
Table `Weather`: id(int, primary key), recordDate(date), temperature(int).\
This table contains information about the temperature on a certain day.\

&NewLine;
Goal: Write an SQL query to find all dates' Id with higher temperatures compared to its previous dates (yesterday).\
Return the result table in any order.


&NewLine;
&NewLine;



**511. Game Play Analysis I**\
Table `Activity`: (player_id,event_date) is the primary key, device_id(int),games_played(int).\
Each row is a record of a player who logged in and played a number of games (possibily 0) before logging out on someday using some device.\


&NewLine;
**Goal:** Write an SQL query to report the first login date for each player. \
Result in any order.\




&NewLine;
&NewLine;



**512. Game Play Analysis II**\
Table `Activity`: (player_id,event_date) is the primary key. device_id(int), games_played(int).\
Each row is a record of a player who logged in and played a number of games (possibily 0) before logging out on someday using some device.\


&NewLine;
**Goal:** Write an SQL query to report the device that is first logged in for each player.\
Return the results in any order.\


&NewLine;
&NewLine;


**577. Employee Bonus**\
Table `Employee`: empId(int, primary key), name(varchar), supervisor(int), salary(int).\
Each row of this table indicates the name and the ID of an employee in addition to their salary and the id of their manager.\
Table `Bonus`: empId(int, primary key, foreign key to empId from the Employee table), bonus(int).\
Each row of this table contains the id of an employee and their respective bonus.\

&NewLine;
**Goal:**Write an SQL query to report the name and bonus amount of each employee with a bonus less than 1000.\
Return the result table in any order.



&NewLine;
&NewLine;


**584. FindCustomer Referee**\
Table `Customer`: id(int, primary key), name(varchar),referee_id(int)\
Each row of this table indicates the id of a customer, their name, and the id of the customer who referred them.

&NewLine;
Goal:Write an SQL query to report the IDs of the customer that are not referred by the customer with id = 2.\
Return the result table in any order.


&NewLine;
&NewLine;

**586. Customer Placing the Largest Number of Orders**\
Table `Orders`: order_numeber(int,primary key), customer_number(int).\

&NewLine;
**Goal:** Write an SQL query to find the customer_number for the customer who has placed the largest number of orders.\
The test cases are generated so that exactly one customer will have placed more orders than any other customer.



&NewLine;
&NewLine;

**595. Big Countries**\
Table `World`: name(varchar, primary key), continent(varchar), area(int), population(int), gdp(int).\
A country is big if:\
* it has an area of at least 3000000 $km^{2}$ or\
* it has a population at least 25000000

&NewLine;
**Goal:** Write an SQL query to report the name, population, and area of the big countries.\
Return the result table in any order.


&NewLine;
&NewLine;


**596. Classes More Than 5 Students**\
Table `Courses`: (student,class) is the primary key. 
Each row of this table indicates the name of a student and the class in which they are enrolled.\

&NewLine;
**Goal:** Write an SQL query to report all the classes that have at least five students.\
Return the result table in any order.


&NewLine;
&NewLine;


**597. Friend Requests I: Overall Acceptance Rate**\
Table `FriendRequest`: sender_id(int),send_to_id(int),request_date(date), there is no primary key for the table, it may contain duplicates.\
This table contains the ID of the user who sent the request, the ID of the user who received the request, and the date of the request.\
Table `RequestAccepted`: requester_id(int),accepter_id(int),accept_date(date), there is no primary key for this table, it may contain duplicates.\
This table contains the ID of the user who sent the request, the ID of the user who received the request, and the date when the request was accepted.\

&NewLine;
**Goal:** Write an SQL query to find the overall acceptance rate of requests, which is the number of acceptance divided by the number of requests. Return the answer rounded to 2 decimals places.

**Note that:**

The accepted requests are not necessarily from the table `friend_request`. In this case, Count the total accepted requests (no matter whether they are in the original requests), and divide it by the number of requests to get the acceptance rate.
It is possible that a sender sends multiple requests to the same receiver, and a request could be accepted more than once. In this case, the ‘duplicated’ requests or acceptances are only counted once.
If there are no requests at all, you should return 0.00 as the accept_rate.

&NewLine;
&NewLine;



**603. Consecutive Available Seats**\
Table `Cinema`: seat_id(int,auto-increment primary key column for this table)\
Each row of this table indicates whether the $i^{th}$ seat is free or not. 1 means free while 0 means occupied.\


&NewLine;
**Goal:** Write an SQL query to report all the consecutive available seats in the cinema.\
Return the result table ordered by `seat_id` in ascending order.

&NewLine;
&NewLine;



**607. Sales Person**\
Table `SalesPerson`: sales_id(int,primary key), name(varchar), salary(int), commission_rate(int), hire_date(date)\
Each row of this table indicates the name and the ID of a salesperson alongside their salary, commission rate, and hire date.\
Table `Company`: com_id(int,primary key), name(varchar),city(varchar)\
Table `Orders`: order_id(int,primary key),com_id(int,foreign key to com_id from the Company table), sales_id(foreign key to cm_id from SalesPerson table), order_date(date), amount(int)\
Each row of this table contains information about one order.

&NewLine;
**Goal:** Write an SQL query to report the names of all the salespersons who did not have any orders related to the company with the name "RED".\
Return the result table in any order.


&NewLine;
&NewLine;



**610. Triangle Judgement**\
Table `Traingle`: (x,y,z) is the primary key column for this table. Each row of this table contains the lengths of three line segments.\


&NewLine;
**Goal:** Write an SQL query to report for every three line segments whether they can form a triangle.\
Return the result table in any order.

&NewLine;
&NewLine;



**613. Shortest Distance in a Line**\
Table `Point`: x(int,primary key)\
Each row of this table indicates the position of a point on the x-axis.\

&NewLine;
**Goal:** Write an SQL query to report the shortest distance between any two points from the `Point` table.


&NewLine;
&NewLine;



**619. Biggest Single Number**\
Table `MyNumbers`: num(int), no primary key for this table, it may contain duplicates.

&NewLine; 
**Goal:** A single number is a number that appeared only once in the MyNumbers table.\
Write an SQL query to report the largest single number. If there is no single number, report null.


&NewLine;
&NewLine;



**620. Not Boring Movies**\
Table `Cinema`: id(int,primary key), movie(varchar),description(varchar),rating(float)\
Each row contains information about the name of a movie, its genre, and its rating. Rating is a 2 decimal places float in the range [0,10].


&NewLine; 
**Goal:** Write an SQL query to report the movies with an odd-numbered ID and a description that is not "boring".\
Return the result table ordered by rating in descending order.

&NewLine;
&NewLine;



**627. Swap Salary**\
Table `Salary`: id(int,primary key), sex(ENUM, type ('m','f')). This table contains information about an employee.\

&NewLine; 
**Goal:** Write an SQL query to swap all 'f' and 'm' values (i.e., change all 'f' values to 'm' and vice versa) with a single update statement and no intermediate temporary tables.

Note that you must write a single update statement, do not write any select statement for this problem.


&NewLine;
&NewLine;



**1050. Actors and Directors Who Cooperated At Least Three Times**\
Table `ActorDirector`: timestamp(int,primary key), actor_id(int),director_id(int)\

&NewLine; 
**Goal:** Write a SQL query for a report that provides the pairs (actor_id, director_id) where the actor has cooperated with the director at least three times.\
Return the result table in any order.

&NewLine;
&NewLine;


**1068. Product Sales Analysis I**\
Table `Sales`:(sale_id,year) is primary key, product_id is foreign key to `Product` Table. Each row of this table shows a sale on the product product_id in a certain year. Note the price is per unit.\
Table `Product`: product_id(int, primary key),product_name(varchar)\

&NewLine;
**Goal:** Write an SQL query to report the total quantity sold for every product id.\
Return the results in any order.\

&NewLine;
&NewLine;


**1069. Product Sales Analysis II**\
Table `Sales`:(sale_id,year) is primary key, product_id is foreign key to `Product` Table. Each row of this table shows a sale on the product product_id in a certain year. Note the price is per unit.\
Table `Product`: product_id(int, primary key),product_name(varchar)\

&NewLine;
**Goal:** Write an SQL query to report the product_name, year, price for each sale_id in the `Sales` table.\
Return the results in any order.\

&NewLine;
&NewLine;



**1075. Project Employees I**\
Table `Project`: (project_id,employee_id) is the primary key, employee_id is a foreign key to `Employee` table. Each row indicates the employee with employee_id is working on the project with project_id.\
Table `Employee`: employee_id is the primary key, name(varchar),experience_years(int)\

&NewLine;
**Goal:** Write an SQL query to report the average experience years of all the employees for each project, rounded to 2 digits.\
Return the result table in any order.\

&NewLine;
&NewLine;


**1076. Project Employees II**\
Table `Project`: (project_id,employee_id) is the primary key, employee_id is a foreign key to `Employee` table. Each row indicates the employee with employee_id is working on the project with project_id.\
Table `Employee`: employee_id is the primary key, name(varchar),experience_years(int)\

&NewLine;
**Goal:** Write an SQL query to report all the projects taht have the most employees.\
Return the results in any order.\

&NewLine;
&NewLine;


**1082. Sales Analysis I**\
Table `Product`: product_id(int,primary key),product_name(varchar),unit_price(int).\
Table `Sales`: seller_id(int), product_id(foreign key to `Product` table, buyer_id(int),sale_date(int),quantity(int),price(int). There is no primary key, it cna have repeated rows.\

&NewLine;
**Goal:** Write an SQL query to report the best seller by total sales price, if there is a tie, report them all.\
Return the result table in any order.\

&NewLine;
&NewLine;


**1083. Sales Analysis II**\
Table `Product`: product_id(int,primary key),product_name(varchar),unit_price(int).\
Table `Sales`: seller_id(int), product_id(foreign key to `Product` table, buyer_id(int),sale_date(int),quantity(int),price(int). There is no primary key, it cna have repeated rows.\

&NewLine;
**Goal:** Write an SQL query to report the buyers who have bought S8 but not iPhone. Note that S8 and iPhone are products present in the `Product` table.\
Return the result table in any order.\

&NewLine;
&NewLine;



**1084. Sales Analysis III**\
Table `Product`: product_id(int,primary key),product_name(varchar),unit_price(int).\
Table `Sales`: seller_id(int), product_id(foreign key to `Product` table, buyer_id(int),sale_date(int),quantity(int),price(int). There is no primary key, it cna have repeated rows.\

&NewLine;
**Goal:** Write an SQL query to report the products that were only sold in the spring of 2019. That is, between 2019-01-01 and 2019-03-31 inclusive.\
Return the result table in any order.\

&NewLine;
&NewLine;



**1113. Reported Posts**\
Table `Actions`: user_id(int),post_id(int),action_date(date),action(enum),extra(varchar). There is no primary key for the table, it may have duplicate rows.\
The action column is an ENUM type of ('view', 'like', 'reaction', 'comment', 'report', 'share').\
The extra column has optional information about the action, such as a reason for the report or a type of reaction.\

&NewLine;
**Goal:** Write an SQL query to report the number of posts reported yesterday for each report reason. Assume today is 2019-07-05.\
Return the result table in any order.\

&NewLine;
&NewLine;



**1141. User Activity for the Past 30 Days I**\
Table `Activity`: user_id(int), session_id(int), activity_date(date), activity_type(enum). There is no primary key for this table, it may have duplicate rows. The activity_type column is an ENUM of type ('open_session','end_session', 'scroll_down', 'send_message').
The table shows the user activities for a social media website.\
Note that each session belongs to exactly one user.\

&NewLine;
**Goal:** Write an SQL query to find the daily active user count for a period of 30 days ending 2019-07-27 inclusively. A user was active on someday if they made at least one activity on that day.\
Return the result in any order.\

&NewLine;
&NewLine;



**1142. User Activity for the Past 30 Days II**\
Table `Activity`: user_id(int), session_id(int), activity_date(date), activity_type(enum). There is no primary key for this table, it may have duplicate rows. The activity_type column is an ENUM of type ('open_session','end_session', 'scroll_down', 'send_message').
The table shows the user activities for a social media website.\
Note that each session belongs to exactly one user.\

&NewLine;
**Goal:** Write an SQL query to find the average number of sessions per user for a period of 30 days ending 2019-07-27 inclusively, rounded to 2 decimal places. The sessions we want to count for a user are those with at least one activity in that time period.\

&NewLine;
&NewLine;

**1148. Article ViewsI**\
Table `Views`: article_id(int),author_id(int),viewer_id(int),view_date(date). Each row of this table indicates that some viewer viewed an article (written by some author) on some date.\
Note that equal `author_id` and `viewer_id` indicate the same person.


&NewLine;
**Goal:** Write an SQL query to find all the authors that viewed at least one of their own articles.\
Return the result table sorted by id in ascending order.\

&NewLine;
&NewLine;


**1173. Immediate Food Delivery I**\
Table `Delivery`: deilivery_id(int,primary key), customer_id(int), order_date(date),customer_pref_delivery_date(date). The table holds information about food delivery to customers that make orders at some date and specify a preferred delivery date (on the same order date or after it).\

\
&NewLine;
**Goal:** If the customer's preferred delivery date is the same as the order date, then the order is called immediate; otherwise, it is called scheduled.\
Write an SQL query to find the percentage of immediate orders in the table, rounded to 2 decimal places.\


&NewLine;
&NewLine;

**1179. Reformat Department Table**\
Table `Department`: (id,month) is the primary key, revenue(int). The table has information about the revenue of each department per month. The month has values in ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].

&NewLine;
**Goal:** Write an SQL query to reformat the table such that there is a department id column and a revenue column for each month.\
Return the result table in any order.\


&NewLine;
&NewLine;



**1211. Queries Quality and Percentage**\
Table `Queries`: query_name(varchar), result(varchar),position(int),rating(int). There is no primary key for this table.\
This table contains information collected from some queries on a database.\
The position column has a value from 1 to 500.\
The rating column has a value from 1 to 5. Query with rating less than 3 is a poor query.

\
&NewLine;
**Goal:** 
We define query `quality` as:

The average of the ratio between query rating and its position.

We also define `poor query percentage` as:

The percentage of all queries with rating less than 3.

Write an SQL query to find each `query_name`, the `quality` and `poor_query_percentage`.

Both `quality` and `poor_query_percentage` should be rounded to 2 decimal places.

Return the result table in any order.

&NewLine;
&NewLine;



**1241. Number of Comments per Post**\
Table `Submissions`: sub_id(int),parent_id(int). There is no primary key for this table, it may have duplicates.\
Each row can be a post or comment on the post.\
parent_id is null for posts.\
parent_id for comments is sub_id for another post in the table.\

\
&NewLine;
**Goal:** Write an SQL query to find the number of comments per post. The result table should contain `post_id` and its corresponding `number_of_comments`.

The `Submissions` table may contain duplicate comments. You should count the number of **unique comments per post**.

The `Submissions` table may contain duplicate posts. You should treat them as one post.

The result table should be ordered by `post_id` in ascending order.

&NewLine;
&NewLine;

**1251. Average Selling Price**\
Table `Prices`: (product_id,start_date,end_date) is the primary key, price(int). Each row of the table is the price of the product_id iin the period from start_date to end_date. For each product_id there will be no two overlapping periods. That means there will be no two intersecting periods for the same product_id.\
Table `UnitSold`: product_id(int),purchase_date(date),units(int). There is no primary key for the table, it may contains duplicates.\

&NewLine;
**Goal:** Write an SQL query to find the average selling price for each product. average_price should be rounded to 2 decimal places.\
Return the result table in any order.\


&NewLine;
&NewLine;


**1280. Students and Examinations**\
Table `Students`: studnet_id(int, primary key),student_name\
Table `Subjects`: subject_name(varchar,primary key)\
Table `Examinations`: student_id(int),subject_name(varchar).There is no primary key for this table, it may contain duplicates.\

&NewLine;
**Goal:** Write an SQL query to find the number of times each student attended each exam.\
Return the result table ordered by `student_id` and `subject_name`.\

&NewLine;
&NewLine;


**1294. Weather Type in Each Country**\
Table `Countries`: country_id(int, primary key), country_name(varchar)\
Table `Weather`: (country_id,day) is the primary key, weather_state(int). Each row of the table indicates the weather state in a country for one day.\

&NewLine;
**Goal:** Write an SQL query to find the type of weather in each country for November 2019.\
The type of weather is:\
Cold--weather_state<15, Hot--weather_state>=25, Warm--otherwise.\


&NewLine;
&NewLine;

**1303. Find the Team Size**\
Table `Employee`: employee_id(int,primary key), team_id(int). Each row of this table contains the ID of each employee and their respective team.\

&NewLine;
**Goal:** Write an SQL query to find the team size of each of the employees.\
Return result table in any order.\

&NewLine;
&NewLine;


**1322. Ads Performance**\
Table `Ads`: (ad_id,user_id) is the primary key. Each row of this table contains the ID of an Ad, the ID of a user, and the action taken by this user regarding to the Ad. The action column is an ENUM type of ('Clicked','Viewed','Ignored').\

A company is running Ads and wants to calculate the performance of each Ad. Performance of the Ad is measured using Click-through rate(CTR) where:

$$CTR= \begin{cases}
 0 & \text{ if } clicks+views=0 \\ 
 \frac{clicks}{clicks+views}\times 100& \text{ if } otherwise
\end{cases}$$

&NewLine;
**Goal:** Write an SQL query to find the ctr of each Ad. Round ctr to two decimal points.\
Return the result table ordered by ctr in descending order and by ad_id in ascending order in case of a tie.\

&NewLine;
&NewLine;



**1327. List the Products Ordered In a Period**\
Table `Products`: product_id(int,primary key),product_name(varchar),product_category(varchar). This table contains data about the company's products.\
Table `Orders`: product_id(int, foreign key to Products table),order_date(date),unit(int). There is no primary key for this table, it may contains duplicate rows.\

&NewLine;
**Goal:** Write an SQL query to get the names of products that have at least 100 units ordered in February 2020 and their amount.\
Return result table in any order.\


&NewLine;
&NewLine;


**1350. Studnets With Invalid Departments**\
Table `Departments`: id(int,primary key), name(varchar)\
Table `Students`: id(int,primary key), name(varchar), department_id(int)\

&NewLine;
**Goal:** Write an SQL query to find the id and the name of all students who are enrolled in departments that no longer exist.\
Return the result table in any order.\


&NewLine;
&NewLine;

**1378. Replace Employee ID with the Unique Identifier**\
Table `Employees`: id(int,primary key), name(varchar)\
Table `EmployeeUNI`: (id,unique_id) is the primary key. Each row contains the id and the corresponding unique id of an employee in the company.\

&NewLine;
**Goal:** Write an SQL query to show the unique ID of each user, If a user does not have a unique ID replace just show null.\
Return the result table in any order.\

&NewLine;
&NewLine;


**1407. Top Travellers**\
Table `Users`: id(int,primary key),name(varchar)\
Table `Rides`: id(int, primary key), user_id(int), distance(int)\

&NewLine;
**Goal:** Write an SQL query to report the distance traveled by each user.\
Return the result table ordered by travelled_distance in descending order, if two or more users traveled the same distance, order them by their `name` in ascending order.\

&NewLine;
&NewLine;


**1421. NPV Queries**\
Table `NPV`: (id,year) is the primary key, npv(int). The table has information about the id and the year of each inventory and the corresponding net present value.\
Table `Queries`: (id,year) is the primary key. The table has information about the id and the year of each inventory query.\

&NewLine;
**Goal:** Write an SQL query to find the `npv` of each query of the `Queries` table.\
Return the table in any order.\

&NewLine;
&NewLine;


**1435. Create a Session Bar Chart**\
Table `Sessions`: session_id(int,primary key),duration(int,is the time in seconds that a user has visited the application)\

&NewLine;
**Goal:** Write an SQL query to report how long a user visits your application. You decided to create bins of "[0-5>", "[5-10>", "[10-15>", and "15 minutes or more" and count the number of sessions on it.\
Write an SQL query to report the (bin, total).\
Return the result table in any order.\

&NewLine;
&NewLine;


**1484. Group Sold Products By the Date**\
Table `Activities`: sell_date(date),product(varchar). There is no primary key for the table, it may contain duplicates.\

&NewLine;
**Goal:** Write an SQL query to find for each date the number of different products sold and their names.\
The sold products names for each date should be sorted lexicographically.\
Return the result table ordered by `sell_date`.\

&NewLine;
&NewLine;


**1495. Friendly Movies Streamed Last Month**\
Table `TVProgram`: (program_date,content_id) is the primary key. content_id(int), is the id of the program in some channel on the TV.\
Table `Content`: content_id(varchar,primary key), title(varchar),Kids_content(enum,'Y' means the content for kids otherwise 'N' is not content for kids), content_type(varchar)\

&NewLine;
**Goal:** Write an SQL query to report distinct titles of the kid-friendly movies streamed in June 2020.\
Return the result table in any order.\

&NewLine;
&NewLine;




