---
title: "Leetcode Easy Questions -- Q175-Q577"
author: "Wenxiao Zhou"
date: "3/23/2022"
output: html_document
---

**175. Combine Two Tables**\
Table `Person`: personId(int,primary key), lastName(varchar), firstName(varchar)\
This table contains information about the ID of some persons and their names.\
Table `Address`: addressId(int,primary key), personId(int), city(varchar), state(varchar)
Each row contains information about the city and state of one person with ID=PersonId

&NewLine;
**Goal:** Write an SQL query to report the `first name, last name, city, and state` of each person in the `Person` table. If the address of a `personId` is not present in the Address table, report null instead.\
Return the result table in any order.

&NewLine;
&NewLine;

**181. Employees Earning More Than Their Managers**\
Table `Employee`: id(int,primary key), name(varchar), salary(int), managerId(int)\

&NewLine;
**Goal:** Write an SQL query to find the employees who earn more than their managers.\
Return the result table in any order.


&NewLine;
&NewLine;



**182. Duplicate Emails**\
Table `Person`: id(int, primary key), email(varchar)\
Each row of this table contains an email. The emails will not contain uppercase letters.\

&NewLine;
Goal: Write an SQL query to report all the duplicate emails. Return the result table in any order.\



&NewLine;
&NewLine;

**183. Customers Who Never Order**\
Table `Customers`: id(int, primary key), name(varchar)\
Table `Orders`: id(int,primary key), customerId(int, foreign key of the ID from Customers table)\
Each row of this table indicates the ID of an order and the ID of the customer who ordered it.
 
&NewLine;
**Goal:** Write an SQL query to report all customers who never order anything.Return the result table in any order.



&NewLine;
&NewLine;

**196. Delete Duplicate Emails**\
Table `Person`: id(int, primary key), email(varchar)\

&NewLine;
**Goal:** Write an SQL query to delete all the duplicate emails, keeping only one unique email with the smallest id. Note that you are supposed to write a DELETE statement and not a SELECT one.\
Return the result table in any order.


&NewLine;
&NewLine;


**197. Rising Temperature**\
Table `Weather`: id(int, primary key), recordDate(date), temperature(int).\
This table contains information about the temperature on a certain day.\

&NewLine;
Goal: Write an SQL query to find all dates' Id with higher temperatures compared to its previous dates (yesterday).\
Return the result table in any order.


&NewLine;
&NewLine;



**511. Game Play Analysis I**\
Table `Activity`: (player_id,event_date) is the primary key, device_id(int),games_played(int).\
Each row is a record of a player who logged in and played a number of games (possibily 0) before logging out on someday using some device.\


&NewLine;
**Goal:** Write an SQL query to report the first login date for each player. \
Result in any order.\




&NewLine;
&NewLine;



**512. Game Play Analysis II**\
Table `Activity`: (player_id,event_date) is the primary key. device_id(int), games_played(int).\
Each row is a record of a player who logged in and played a number of games (possibily 0) before logging out on someday using some device.\


&NewLine;
**Goal:** Write an SQL query to report the device that is first logged in for each player.\
Return the results in any order.\


&NewLine;
&NewLine;


**577. Employee Bonus**\
Table `Employee`: empId(int, primary key), name(varchar), supervisor(int), salary(int).\
Each row of this table indicates the name and the ID of an employee in addition to their salary and the id of their manager.\
Table `Bonus`: empId(int, primary key, foreign key to empId from the Employee table), bonus(int).\
Each row of this table contains the id of an employee and their respective bonus.\

&NewLine;
**Goal:**Write an SQL query to report the name and bonus amount of each employee with a bonus less than 1000.\
Return the result table in any order.





